export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';

export const SET_VIEW_MODE = 'VIEW_MODE';
export const TOGGLE_MY_PROFILE = 'TOGGLE_MY_PROFILE';