export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';

export const SET_VIEW_MODE = 'VIEW_MODE';
export const TOGGLE_MY_PROFILE = 'TOGGLE_MY_PROFILE';

export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const DELETE_POSTS = 'DELETE_POSTS';
export const SET_SUBREDDIT = 'SET_SUBREDDIT';