export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';

export const SET_VIEW_MODE = 'VIEW_MODE';
export const TOGGLE_MY_PROFILE = 'TOGGLE_MY_PROFILE';

export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const DELETE_POSTS = 'DELETE_POSTS';
export const FETCH_POST_BY_ID_START = 'FETCH_POST_BY_ID_START';
export const FETCH_POST_BY_ID_SUCCESS = 'FETCH_POST_BY_ID_SUCCESS';
export const FETCH_POST_BY_ID_FAIL = 'FETCH_POST_BY_ID_FAIL';

export const SAVE_POST_START = 'SAVE_POST_START';
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS';
export const SAVE_POST_FAIL = 'SAVE_POST_FAIL';
export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';
export const FETCH_SAVED_POSTS_START = 'FETCH_SAVED_POSTS_START';
export const FETCH_SAVED_POSTS_SUCCESS = 'FETCH_SAVED_POSTS_SUCCESS';
export const FETCH_SAVED_POSTS_FAIL = 'FETCH_SAVED_POSTS_FAIL';
export const REMOVE_SAVED_POSTS = 'REMOVE_SAVED_POSTS';